ALTER TABLE BD_OPPGAVE ADD COLUMN ytelsetype VARCHAR(255);
UPDATE BD_OPPGAVE WHERE ytelsetype IS NULL SET ytelsetype = 'UNGDOMSPROGRAMYTELSEN';
ALTER TABLE BD_OPPGAVE ALTER COLUMN ytelsetype SET NOT NULL;
