ALTER TABLE BD_OPPGAVE ADD COLUMN ytelsetype VARCHAR(255);
UPDATE BD_OPPGAVE SET ytelsetype = 'UNGDOMSPROGRAMYTELSEN' WHERE ytelsetype IS NULL;
ALTER TABLE BD_OPPGAVE ALTER COLUMN ytelsetype SET NOT NULL;
